Project3/force-app/main/default/objects/Monthly_Statement__c/Monthly_Statement__c.object-meta.xml
<CustomObject>
    <description>Object that stores records of the monthly statements tenants pay on their rental property.</description>
    <label>Monthly Statement</label>
    <nameField>
        <label>Monthly Statement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monthly Statements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project3/force-app/main/default/objects/Monthly_Statement__c/fields/Rental_Property__c.field-meta.xml
<CustomField>
    <fullName>Rental_Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rental Property</label>
    <referenceTo>Rental_Property__c</referenceTo>
    <relationshipLabel>Monthly Statements</relationshipLabel>
    <relationshipName>Monthly_Statements</relationshipName>
    <type>Lookup</type>
</CustomField>

Project3/force-app/main/default/objects/Rental_Property__c/Rental_Property__c.object-meta.xml
<CustomObject>
    <description>Object that stores available and occupied rental properties.</description>
    <label>Rental Property</label>
    <nameField>
        <label>Rental Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rental Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project3/force-app/main/default/classes/MonthlyStatementController.cls
public with sharing class MonthlyStatementController {
  @AuraEnabled(cacheable=true)
  public static List<Monthly_Statement__c> getMonthlyStatementsForLoggedInContact() {
    // Get the current user's contact ID
    Id contactId = [SELECT ContactId FROM User WHERE Id = :UserInfo.getUserId()].ContactId;
    System.debug(contactId);
    if (contactId == null) {
      return new List<Monthly_Statement__c>();
    }
    // Query Monthly_Statement__c for the current user's contact
    return [
      SELECT Id, Name, Rental_Property__c, Amount_Charged__c
      FROM Monthly_Statement__c
      WHERE Contact__c = :contactId
      LIMIT 10
    ];
  }
}